# Generated by Django 4.0.6 on 2022-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('molecule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('molecular_formula', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Molecule',
            },
        ),
    ]
