# Generated by Django 4.0.6 on 2022-07-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lewis_structures_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='molecule',
            table='molecule',
        ),
    ]
